version: '3.8'

services:
  nextjs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3010:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://flask-api:5000
    networks:
      - drimsoft-data-lake_datalake
    restart: unless-stopped

networks:
  drimsoft-data-lake_datalake:
    external: true
